version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/file/Dockerfile
    command: "CompileDaemon --build='make install' --command=scooter"
    env_file:
      - docker/env/.env.app
    container_name: scooter-http-app
    ports:
      - "9999:80"
    volumes:
      - ./:/scooter:delegated
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: scooter-database
    volumes:
      - ./docker/scripts/create_db_if_not_exists.sh:/docker-entrypoint-create_db_if_not_exists.sh:delegated
    ports:
      - "3308:3306"
    env_file:
      - docker/env/.env.database
